# Generated by Django 5.0.7 on 2024-07-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_updated_at_risk_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='last_assessment_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='risk',
            name='risk_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='spend',
            name='relationship_type',
            field=models.CharField(choices=[('DIRECT', 'Direct'), ('THIRD PARTY', 'Third Party')], default='DIRECT', max_length=50),
        ),
        migrations.AddField(
            model_name='vendor',
            name='average_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='vendor',
            name='contract_type',
            field=models.CharField(choices=[('FIXED', 'Fixed Price'), ('TIME', 'Time and Materials'), ('COST', 'Cost Plus')], default='FIXED', max_length=10),
        ),
        migrations.AddField(
            model_name='vendor',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
