# Generated by Django 5.0.7 on 2024-07-31 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_risk_last_assessment_date_risk_risk_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='country',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
