# Generated by Django 5.0.7 on 2024-07-31 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_vendor_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risk',
            name='last_assessment_date',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='risk_score',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='average_discount',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='contract_type',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='rating',
        ),
    ]
