# Generated by Django 5.0.7 on 2024-07-31 14:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_risk_last_assessment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='average_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='vendor',
            name='contract_type',
            field=models.CharField(choices=[('FIXED', 'Fixed Price'), ('TIME', 'Time and Materials'), ('COST', 'Cost Plus')], default='FIXED', max_length=10),
        ),
        migrations.AddField(
            model_name='vendor',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
