# Generated by Django 5.0.7 on 2024-07-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorimport',
            name='contract_type',
            field=models.CharField(default='FIXED', max_length=10),
        ),
    ]
